---
# tasks file for nginx

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled

- name: Allow SSH
  become: true
  community.general.ufw:
    rule: allow
    port: 80

- name: Allow SSH
  become: true
  community.general.ufw:
    rule: allow
    port: 9000

- name: Allow SSH
  become: true
  community.general.ufw:
    rule: allow
    port: 22

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Delete Default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

# - name: Copy nginx template
#   template:
#     src: nginx-template.j2
#     dest: /etc/nginx/sites-available/frontend
#   notify: Restart nginx